language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4

before_script:
  - "RAILS_ENV=test bundle exec rake app:db:schema:load"

before_install:
  - "gem install bundler"

script: "bundle exec rake"

gemfile:
  - "gemfiles/rails_5_0.gemfile"
  - "gemfiles/rails_5_1.gemfile"
  - "gemfiles/rails_5_2.gemfile"
