# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{judge}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Corcoran"]
  s.date = %q{2011-11-05}
  s.description = %q{Validate forms on the client side, cleanly}
  s.email = %q{joe@tribesports.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "docs/docco.css",
    "docs/judge.html",
    "judge.gemspec",
    "lib/generators/judge/judge_generator.rb",
    "lib/generators/judge/templates/json2.js",
    "lib/generators/judge/templates/judge.js",
    "lib/generators/judge/templates/underscore.js",
    "lib/judge.rb",
    "lib/judge/form_builder.rb",
    "lib/judge/message_collection.rb",
    "lib/judge/validator.rb",
    "lib/judge/validator_collection.rb",
    "lib/tasks/js_tests.rake",
    "spec/javascripts/JudgeSpec.js",
    "spec/javascripts/fixtures/form.html",
    "spec/javascripts/helpers/customMatchers.js",
    "spec/javascripts/helpers/jasmine-jquery.js",
    "spec/javascripts/helpers/jquery-1.5.1.min.js",
    "spec/javascripts/helpers/json2.js",
    "spec/javascripts/helpers/underscore.js",
    "spec/javascripts/support/jasmine.yml",
    "spec/javascripts/support/jasmine_config.rb",
    "spec/javascripts/support/jasmine_runner.rb",
    "spec/javascripts/support/phantomRunner.js",
    "test/setup.rb",
    "test/test_form_builder.rb",
    "test/test_helper.rb",
    "test/test_message_collection.rb",
    "test/test_validator.rb",
    "test/test_validator_collection.rb"
  ]
  s.homepage = %q{http://github.com/joecorcoran/judge}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Simple client side ActiveModel::Validators}
  s.test_files = [
    "spec/javascripts/support/jasmine_config.rb",
    "spec/javascripts/support/jasmine_runner.rb",
    "test/expected_elements.rb",
    "test/setup.rb",
    "test/test_form_builder.rb",
    "test/test_helper.rb",
    "test/test_message_collection.rb",
    "test/test_validator.rb",
    "test/test_validator_collection.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<judge>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.18"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<jasmine>, ["~> 1.0.2"])
      s.add_development_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
      s.add_development_dependency(%q<nokogiri>, ["~> 1.4.7"])
      s.add_development_dependency(%q<json>, ["~> 1.6.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<jasmine>, ["~> 1.0.2"])
      s.add_development_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
      s.add_development_dependency(%q<nokogiri>, ["~> 1.5.0"])
    else
      s.add_dependency(%q<judge>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.18"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<jasmine>, ["~> 1.0.2"])
      s.add_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.7"])
      s.add_dependency(%q<json>, ["~> 1.6.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<jasmine>, ["~> 1.0.2"])
      s.add_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
    end
  else
    s.add_dependency(%q<judge>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.18"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<jasmine>, ["~> 1.0.2"])
    s.add_dependency(%q<rails>, ["~> 3.0.10"])
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.7"])
    s.add_dependency(%q<json>, ["~> 1.6.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<jasmine>, ["~> 1.0.2"])
    s.add_dependency(%q<rails>, ["~> 3.0.10"])
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
  end
end

