---
version: 2.1
jobs:
  build:
    working_directory: ~/judge
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          RAILS_ENV: test
      - image: keinos/sqlite3:3.40.1

    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: judge-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: gem bundle install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: judge-{{ checksum "Gemfile.lock" }}
        paths:
          - bin/bundle

      # Wait for DB
      # - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec appraisal rake db:create
      - run: bundle exec appraisal rake db:migrate

      # Run the tests
      - run: bundle exec appraisal rspec