---
version: 2.1
jobs:
  build:
    working_directory: ~/judge
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
        environment:
          RAILS_ENV: test
      - image: keinos/sqlite3:3.40.1

    steps:
      - checkout

      - run: bundle install
      - run: bundle exec appraisal install

      - run: bundle exec appraisal rake db:create
      - run: bundle exec appraisal rake db:migrate

      - run: bundle exec appraisal rspec

# For more info on Matrix Jobs:
# https://circleci.com/blog/circleci-matrix-jobs/
workflows:
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ['2.5', '2.7']
